services:
  - type: web
    name: king-bug-md
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node sever.js
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: "20"
